import "./globals.css"
import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { Toaster } from "@/app/components/ui/sonner"
import NextAuthProvider from "@/app/components/wrapper/NextAuthProvider"


const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NextAuthProvider>
          {children}
          <Toaster/>
        </NextAuthProvider>
      </body>
    </html>
  );
}
